### PR TITLE
Fixed ycqlsh/cqlsh cli to accept python 3.10+

### LINKED ISSUE #11: Python 3.10 support
It seems that Python 3.10 is unsupported.

This section of the wrapper script considers `3.10` to be unsupported because it is numerically less than `3.6`:
```sh
if [ "$version" = "3.6" ] || [ "$version" \> "3.6" ] || [ "$version" = "2.7" ]; then
    echo "supported"
else
    echo "unsupported"
fi
```

If I patch the script so that it considers 3.10 to be supported, then it instead fails with this error:
```
Traceback (most recent call last):
  File "C:\Work\Software\cqlsh\bin\ycqlsh.py", line 160, in <module>
    from cassandra.cluster import Cluster
  File "C:\Work\Software\cqlsh\bin\..\lib\cassandra-driver-internal-only-3.13.0.3-8d292edb.zip/cassandra-driver\3.13.0.3-8d292edb\cassandra\cluster.py", line 22, in <module>
ImportError: cannot import name 'Mapping' from 'collections' (C:\Program Files\Python310\lib\collections\__init__.py)
```

### PR DESCRIPTION
**Pull request by HarshDaryani896**
**Resolves #11** 

**Description**
If you ONLY have python 3.10+ in your system, ycqlsh/cqlsh used to fail to start with `No appropriate Python interpreter found.`

The reason is that it used to do string comparison when checking the version, this PR fixes this by splitting the version number into two integers, `$version_major` and `$version_minor` and then compare them to `3` and `6` respectively.

This PR also updates the Cassandra python driver .zip file which cqlsh uses internally, this is done to resolve `ImportError: cannot import name 'Mapping' from 'collections'`  which comes up for Python 3.10+ .

### CODE REVIEW

**Comment by HarshDaryani896** [comment]
The updated Cassandra python driver .zip file is of upstream python-driver. Looking into changing it to use our fork of yugabyte/Cassandra-python-driver. 
Our fork was last updated last year but there has not been a release since past couple of years.  Checking this with @Sfurti-yb  as she has the last commit.

**Review by OlegLoginov — APPROVED** [review]
LGTM. Only one question:
```
   # shellcheck disable=SC2039
    # shellcheck disable=SC2072
```
Why should we remove this? (If it's still actual - please return it back.)

**Review by OlegLoginov — APPROVED** [review]
If possible - please use previous archive format name - like:
```
cassandra-driver-internal-only-3.13.0.3-8d292edb.zip
```
So should be for the new file: `cassandra-driver-internal-only-3.25.0.0-abcd1234.zip`

**Comment by HarshDaryani896** [comment]
> LGTM. Only one question:
> 
> ```
>    # shellcheck disable=SC2039
>     # shellcheck disable=SC2072
> ```
> 
> Why should we remove this? (If it's still actual - please return it back.)

These are not required anymore, as they were needed for `\>` in: 
`if [ "$version" = "3.6" ] || [ "$version" \> "3.6" ] || [ "$version" = "2.7" ]; then`
which is now changed to : 
`if [ "$major_version" = 3 ] && [ "$minor_version" -ge 6 ] || [ "$version" = "2.7" ]; then`

**Pull request merged**
